import { Header } from "./components/Header";
import { TopLogo } from "./components/TopLogo";
import Footer from "./components/Footer";
import BottomContent from "./components/BottomContent";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-center items-center">
        <TopLogo />
        <Header />
        <div className="w-9/12">{children}</div>
        <BottomContent />
        <Footer />
      </body>
    </html>
  );
}
