import { Header } from "./components/Header";
import { TopLogo } from "./components/TopLogo";
import { VideosNav } from "./components/VideosNav";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TopLogo />
        <Header />
        <div className="w-full flex items-center justify-center">{children}</div>
      </body>
    </html>
  );
}
